### ISSUE TITLE
Consider removing pre-commit hooks

### ISSUE THREAD

**Issue by SimonBoothroyd** [mattwthompson/openff-utilities#8]
## Descriptions

In the past a number of developers in the org have expressed caution over including pre-commit hooks (I think mainly due to them potentially running binaries on users computers that they may not want run?), so it may be best just to remove the hooks for now until the OpenFF software stack uniformly adopts this.

**Comment by mattwthompson** [comment]
I grant it's not appropriate for a package that is not "mine," but I'm not sure I see the harm in the file sticking around (and documenting its use as optional)? Tracking the files at least ensures me the convenience of knowing that the file I use matches the linting workflow of the project. I could, though, just keep the files floating around locally for me?

I'll likely make a push for this change in the future, and now there is [pre-commit ci](https://pre-commit.ci) that solves the problem of developers not using these hooks locally. See for example [automatic](https://github.com/mosdef-hub/mbuild/pull/892) fixes during a PR and Dependabot-like [autoupdate](https://github.com/mosdef-hub/mbuild/pull/906) PRs when hooks get updated. This should (?) solve the problem of people not liking an automated tool running binaries on their code. It won't solve the problem of people generally not trusting automation (I don't think there is much of that perspective within OpenFF, but past me didn't like it). Something to consider down the road.

**Comment by SimonBoothroyd** [comment]
Fixed by #9
